apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: health-probes-deployment
  name: health-probes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-probes-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: health-probes-deployment
    spec:
      containers:
      - image: health-probes
        name: health-probes
        resources: {}
status: {}
