apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      track: canary
  template:
    metadata:
      labels:
        track: canary
    spec:
      containers:
      - name: canary
        image: ckad:canary
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" # 128 MB
            cpu: "200m" # 200 millicpu (.2 cpu or 20% of the cpu)