kind: Service
apiVersion: v1
metadata:
  name: public-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: blue
  ports:
    - port: 80
      targetPort: 80
